git-check-repos: allow `git fetch` to fail
It may happen that the remote is not accessible. In this case the script
should continue but the error message is printed to stderr.

diff --git a/git-check-repos b/git-check-repos
--- a/git-check-repos
+++ b/git-check-repos
@@ -63,7 +63,8 @@ main () {
 
         if [ "$do_fetch" -eq 1 ]
         then
-            git -C "$repo_path" fetch
+            # Allow fetch to fail, maybe the remote is not accessible
+            git -C "$repo_path" fetch || true
         fi
 
         echo "$(get_status_upstream_branch "$repo_path")" "$repo_path"
