bash/prompt: indicate if HTTP proxy is set
At work we have a HTTP proxy in use. By default I don't want to send my
traffic to it. But when I do, an indicator should be shown.

The function get_proxy() has to return the exit status of the previous
command. If we didn't do that the exit status would be overriden by
get_proxy(). We don't want this because get_exit_status_color() wants to
know the exit status of the actual command.

diff --git a/.config/bash/prompt b/.config/bash/prompt
--- a/.config/bash/prompt
+++ b/.config/bash/prompt
@@ -1,5 +1,6 @@
 # set bash prompt (PS1)
 DEFAULT='\033[0m'
+BLUE='\033[1;34m'
 RED='\033[1;31m'
 GREEN='\033[1;32m'
 YELLOW='\033[1;33m'
@@ -10,6 +11,18 @@ get_user_color () {
         root) echo "\[$RED\]" ;;
         *)    echo "\[$GREEN\]" ;;
     esac
+}
+
+get_proxy () {
+    # preserve exit status
+    local exit="$?"
+
+    if [ -n "$http_proxy" ] || [ -n "$https_proxy" ]
+    then
+        printf "%s" '(P)'
+    fi
+
+    return "$exit"
 }
 
 get_exit_status_color () {
@@ -53,6 +66,7 @@ PS1+="\[$DEFAULT\]@"
 PS1+="$(word_to_color "$HOSTNAME")\h"
 PS1+="\[$DEFAULT\]:"
 PS1+="\[$YELLOW\]\w"
-PS1+="\[$CYAN\]$branch"
+PS1+="\[$CYAN\]$branch "
+PS1+="\[$BLUE\]\$(get_proxy)"
 PS1+="\[\$(get_exit_status_color)\]\n\$"
 PS1+="\[$DEFAULT\] "
